# Generated by Django 5.2.5 on 2025-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nigeria Transport and Logistics Summit and Awards', max_length=200)),
                ('site_logo', models.ImageField(blank=True, help_text='Logo for navigation and footer', null=True, upload_to='site_assets/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon (.ico, .png)', null=True, upload_to='site_assets/')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='hero_images/')),
                ('contact_email', models.EmailField(default='info@tlngsummit.com', max_length=254)),
                ('contact_phone', models.CharField(default='+234 xxx xxx xxxx', max_length=20)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='eventcontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventcontent',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='about_title',
            field=models.CharField(default="Nigeria's Premier Transport & Logistics Event", max_length=200),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='feature_1_description',
            field=models.CharField(default='with 500+ industry professionals', max_length=200),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='feature_1_title',
            field=models.CharField(default='Networking Opportunities', max_length=100),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='feature_2_description',
            field=models.CharField(default='featuring latest technologies and solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='feature_2_title',
            field=models.CharField(default='Innovation Showcase', max_length=100),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='feature_3_description',
            field=models.CharField(default='recognizing excellence in the industry', max_length=200),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='feature_3_title',
            field=models.CharField(default='Awards Ceremony', max_length=100),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='hero_badge_text',
            field=models.CharField(blank=True, help_text="Text for hero badge (e.g., 'Coming Soon')", max_length=100),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_1_label',
            field=models.CharField(default='Attendees', max_length=50),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_1_number',
            field=models.CharField(default='500+', max_length=20),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_2_label',
            field=models.CharField(default='Speakers', max_length=50),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_2_number',
            field=models.CharField(default='50+', max_length=20),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_3_label',
            field=models.CharField(default='Companies', max_length=50),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_3_number',
            field=models.CharField(default='100+', max_length=20),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_4_label',
            field=models.CharField(default='Days', max_length=50),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='stat_4_number',
            field=models.CharField(default='2', max_length=20),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='subtitle',
            field=models.TextField(default="Join industry leaders, innovators, and stakeholders as we shape the future of Nigeria's transport and logistics sector.", help_text='Hero section subtitle/description'),
        ),
        migrations.AlterField(
            model_name='eventcontent',
            name='about_text',
            field=models.TextField(default='The Nigeria Transport and Logistics Summit and Awards brings together industry leaders, innovators, and decision-makers to shape the future of the transport and logistics sector.'),
        ),
    ]
