# Generated by Django 5.2.5 on 2025-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0002_sitesettings_remove_eventcontent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(blank=True, help_text='Image for the about section after hero', null=True, upload_to='about_section/')),
                ('image_alt_text', models.CharField(default='Transport and Logistics', help_text='Alt text for the about section image', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section Content',
                'verbose_name_plural': 'About Section Content',
            },
        ),
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('attendee_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('student', 'Student'), ('media', 'Media')], default='individual', max_length=20)),
                ('ticket_type', models.CharField(choices=[('regular', 'Regular Ticket'), ('vip', 'VIP Ticket'), ('exhibitor', 'Exhibitor Pass')], default='regular', max_length=20)),
                ('dietary_requirements', models.TextField(blank=True, help_text='Any special dietary requirements')),
                ('special_needs', models.TextField(blank=True, help_text='Any accessibility requirements')),
                ('how_did_you_hear', models.CharField(blank=True, help_text='How did you hear about this event?', max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Conference Registration',
                'verbose_name_plural': 'Conference Registrations',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='SummitOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='organizers/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the organization')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Summit Organizer',
                'verbose_name_plural': 'Summit Organizers',
                'ordering': ['order', 'name'],
            },
        ),
    ]
