# Generated by Django 5.2.5 on 2025-08-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0003_aboutsectioncontent_conferenceregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_organizer_logo',
            field=models.ImageField(blank=True, help_text='Primary organizer logo (appears first in navigation)', null=True, upload_to='site_assets/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Main summit logo (appears second in navigation)', null=True, upload_to='site_assets/'),
        ),
    ]
